name: Deploy
on: push

permissions:
  contents: write

jobs:
  build-web:
    name: Build (Web)
    runs-on: ubuntu-latest
    container: ghcr.io/geng-engine/cargo-geng@sha256:ce60c252b0ac348e7dfbd6828d5473d3b6531d67502cf9efa9aece7cada6706c
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo geng build --release --platform web
        env:
          CONNECT: ${{ secrets.CONNECT }}
      - name: Upload artifacts (web)
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: target/geng

  deploy-pages:
    name: Deploy Github Pages
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'nertsal'
    runs-on: ubuntu-latest
    needs:
      - build-web
    permissions:
      contents: write
    environment:
      name: main
      url: https://nertsal.github.io/trail-blazer
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web
